from setuptools import setup, find_packages

setup(
    name="openedx2zim",
    version="0.5.1",
    description="Make zimfile from open edx MOOCs",
    long_description=open("README.md").read(),
    author="dattaz",
    author_email="taz@dattaz.fr",
    url="http://github.com/kiwix/openedx",
    keywords="kiwix zim openedx edx offline",
    license="GPL",
    packages=find_packages(exclude=["contrib", "docs", "tests*"]),
    package_dir={"openedxtozim": "openedxtozim"},
    zip_safe=False,
    include_package_data=True,
    install_requires=[
        "docopt==0.6.2",
        "beautifulsoup4==4.9.1",
        "lxml==4.5.1",
        "webvtt-py==0.4.5",
        "python-slugify==4.0.0",
        "Jinja2==2.11.2",
        "mistune==0.8.4",
        "requests>=2.24,<3.0",
        "iso-639==0.4.5",
        "zimscraperlib>=1.1.2,<1.2",
        "python-magic==0.4.18",
        "youtube_dl",
    ],
    platforms="Linux",
    scripts=["openedx2zim"],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.4",
    ],
)
